### ISSUE TITLE
What is `targetFrameCount` in raw pumpprobe?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/leifer_lab_to_nwb#4]
Some kind of structured table saved as a text file, content looks like

```
4880	6420	7967	9500	11041	12556	14104	15656	17183	18726	20238	21789	23333	24868	26406	27927	29474	31000	32550	34097	35612	37158	38682	40231	41776	43304	44832	46363	47912	49460	50972	52523	54045	55594	57105	58650	60199	61734	63280	64795	66343	67862	69411	70957	72488	74020	75543	77093	78635	80161	81704	83231	84773	86292	87844	89387	90914	92464	93973	95520
```

but no labels or descriptions.

Length seems to match the number of Pharos triggers but the `frameCount` fields are offset. Also doesn't seem to match the indices of the non-zero values from the 'Pharos on' column of `frameSynchronous.txt`

**Comment by emosb** [comment]
Having looked into this briefly, I am also not sure what these volumes indicate since it doesn't match up with the pharos triggers in frameCount or frameSynchronous. I will try and trace if it is used in the code at all

**Comment by CodyCBakerPhD** [comment]
Might not be relevant
