### ISSUE TITLE
Intensity of optogenetic stimulus?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/leifer_lab_to_nwb#6]
Details are given for intensity of the calcium imaging in the methods section, but not for the optogenetic stimulation

**Comment by emosb** [comment]
I can measure this to check that it is still accurate, but in the methods of the Randi paper it is reported that "the power of the laser at the sample was 1.2 mW at 500 kHz" which is referring to the optogenetic stimulus laser pulse

**Comment by CodyCBakerPhD** [comment]
@emosb That is the `power`, which I am indeed using - the `intensity` would be something in `mW/mm^2`, like in the paragraph from the methods section 

> For functional connectivity experiments, an intensity of 1.4 mW mm−2 at the sample plane was used to image GCaMP6s...

**Comment by CodyCBakerPhD** [comment]
@emosb Unless you're saying the intensity is the same in the ogen case as in the imaging case because it's the same laser?

**Comment by CodyCBakerPhD** [comment]
Leaving this empty since it would be too complicated and not worthwhile to report
