### ISSUE TITLE
Outputs of pumpprobe signal extraction

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/leifer_lab_to_nwb#7]
In `pumpprobe/preprocessing` I see a 'responses' folder with dumped `.png` plots of extracted signals, but having trouble finding that data output saved from the `wormdatamodel.signal.extract` function

**Comment by emosb** [comment]
The responses folder is holding .png files which are generated loading in the signal file (and doing additional post-processing and smoothing on this data according to user parameters).

There are multiple files storing the signal, using slightly different parameters/ordering.
If I'm tracing the preprocessing code correctly, it looks like initially the signal is saved to green-prematching.txt (the most raw signal extraction). If the user adds the tag matchless-tracking when running this preprocessing code (which to my knowledge is standard) then the output is saved in green_matchless.txt. *
The green.pickle and green.txt files are both generated as the last step of this preprocessing code - the green.pickle file is what is loaded in while making these .png files

* To clarify matchless tracking, if the neuron cannot be automatically segmented well enough to be tracked over time, then the signal is extracted from a stationary user-defined point which is taken to be the center of the neuron.

**Comment by emosb** [comment]
I believe the green.txt files and green.pickle files should store the same information, just in different formats

**Comment by CodyCBakerPhD** [comment]
This has been explained at this point, thank you
