### ISSUE TITLE
Duplicated but empty binary files across shared 'Hermaphrodite' folder

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/leifer_lab_to_nwb#8]
The `sCMOS_Frames_U16_1024x512.dat` file is present in folders such as `objectivesregistration_20210830_100857` and `redgreen_20210830_102610` but is 0 bytes in each case

**Comment by CodyCBakerPhD** [comment]
`objectivesregistration_20210830_10085` does have, on the other hand, a ~1 GB file `singleVolumes_U16_1024x512`

**Comment by emosb** [comment]
The empty files are not an error as far as I can tell, since it is present in every dataset. I will ask around to find out if the file is necessary or is just created as part of a defunct pipeline.

**Comment by CodyCBakerPhD** [comment]
Oh OK, I'll just add a check for emptiness and treat it the same as 'skip' in my pipeline
